Wayland: Choose output by name
Cloudef/bemenu pull request #146
Opened 2020-12-28 01:42 UTC by fancycade

Allows user to choose the output for bemenu by passing in name with -M flag.

For example:
```
bemenu-run -M eDP-1
```

There might be some cleaning up to do, but overall this works.

2021-01-23 02:48 UTC, Cloudef commented
Would it be possible to somehow reuse the -m option for this? Make it accept both index and string, and document index isn't reliable on wayland?

2021-01-23 02:57 UTC, Cloudef requested changes
Looks good otherwise.

2021-01-23 02:57 UTC, Cloudef commented on client/common/common.c
> +		break;
Indentation wrong

2021-01-23 02:57 UTC, Cloudef commented on client/common/common.c
> +
Whitespace added

2021-01-23 02:57 UTC, Cloudef commented on client/common/common.c
> +    client->fork = (client->force_fork || (bm_renderer_get_priorty(bm_menu_get_renderer(menu)) != BM_PRIO_TERMINAL));
Whitespace added

2021-01-23 02:57 UTC, Cloudef commented on lib/menu.c
> +    if (menu->monitor_name != NULL)
The if branch isn't needed, free is no-op for null pointers.

2021-01-23 02:57 UTC, Cloudef commented on lib/menu.c
> +	free(menu->monitor_name);
Wrong indentation

2021-01-23 02:57 UTC, Cloudef commented on lib/menu.c
> +	if (monitor_name == NULL)
Use `!monitor_name` instead to keep the codebase consistent

2021-01-23 02:57 UTC, Cloudef commented on lib/menu.c
> +	if (menu->monitor_name != NULL) {
Drop the `!= NULL` to keep the codebase consistent

2021-01-23 02:57 UTC, Cloudef commented on lib/menu.c
> +	if (menu->monitor_name != NULL) {
Also use `&& !strcmp(menu->monitor_name, monitor_name)` and you can drop the additional branch below.

2021-01-23 02:57 UTC, Cloudef commented on lib/menu.c
> +	menu->monitor_name = strdup(monitor_name);
Use `bm_strdup` instead to stay portable.

2021-01-23 02:57 UTC, Cloudef commented on lib/renderers/wayland/registry.c
> +    output->name = strdup(name);
Use `bm_strdup` instead to stay portable.

2021-01-23 02:57 UTC, Cloudef commented on lib/renderers/wayland/registry.c
> +    } else if (strcmp(interface, zxdg_output_manager_v1_interface.name) == 0) {
use `!strcmp` instead of `== 0` to stay consistent.

2021-01-23 02:57 UTC, Cloudef commented on lib/renderers/wayland/registry.c
> +	wayland->xdg_output_manager = wl_registry_bind(registry, id, &zxdg_output_manager_v1_interface, 2);
Wrong indentation

2021-01-23 02:57 UTC, Cloudef commented on lib/menu.c
> +}
The body has wrong indentation

2021-01-23 02:57 UTC, Cloudef commented on lib/renderers/wayland/registry.c
> +};
The body has wrong indentation

2021-01-23 02:57 UTC, Cloudef commented on lib/renderers/wayland/registry.c
> +    }
The body has wrong indentation

2021-01-23 02:57 UTC, Cloudef commented on lib/renderers/wayland/wayland.c
> +	if (menu->monitor_name == NULL) {
Use `!menu->monitor_name` instead of `== NULL` for consistency.

2021-01-23 02:57 UTC, Cloudef commented on lib/renderers/wayland/wayland.c
> +		}
Indentation is bonkers

2021-01-23 02:57 UTC, Cloudef commented on lib/renderers/wayland/wayland.c
> +	} else if (!strcmp(menu->monitor_name, output->name) == 0) {
Drop the `!` and `== 0` leaving just `strcmp`

2021-01-28 03:16 UTC, fancycade commented
Took care of the changes. Tried to make the -m option as simple as I could.

2021-01-28 04:42 UTC, Cloudef commented on client/common/common.c
> +	}
Looks good, the indentation still is wrong though.

2021-01-28 04:44 UTC, Cloudef commented
Looks good, the code styling issues still need to be fixed. I can take care of that too however, if it's too much hassle.

2021-02-05 07:28 UTC, Cloudef commented on client/common/common.c
> +        { "monitor-name", required_argument, 0, 'M' },
Not needed anymore.

2021-02-05 07:28 UTC, Cloudef commented on client/common/common.c
> +          " -M, --monitor-name    name of monitor where menu will appear. Wayland only. (wx)\n"
Not needed anymore.

2021-02-05 07:35 UTC, fancycade commented
Didn't realize you had replied so quickly. I'm going to have to look into turning off tabs for next time.

Let me know if I missed something.

2021-02-05 07:36 UTC, Cloudef commented on lib/renderers/wayland/wayland.c
> +	if (!menu->monitor_name) {
Indentation still here is bonkers.

2021-02-05 07:52 UTC, Cloudef approved these changes
Looks good, merging. Thanks!

2021-02-05 07:53 UTC, merged